### ISSUE TITLE
Make cannot find Ruby.pluginspec

### ISSUE THREAD

**Issue by briansprojects** [hugopl/RubyCreator#44]
Make errors with the follow error:

No rule to make target '../Ruby.pluginspec', needed by '/usr/lib/qtcreator/plugins/Ruby.pluginspec'.

**Comment by hugopl** [comment]
Are you trying to compile what branch against what Qt Creator version? Using what Qt?

**Comment by briansprojects** [comment]
This is Qt Creator 3.2.2 with Qt 4.8.7. I used the Master branch.

**Comment by hugopl** [comment]
I just updated the README file, master branch will compile with QtCreator master branch.

I would recommend you to upgrade your QtCreator to 3.4, currently RubyCreator has versions for QtC 3.1 (not tested by me), 3.3 and 3.4, but all new stuff is on 3.4 that you can find in `qtc-3.4` branch. Other are on `qtc-3.1` and `qtc-3.3` branches.

Ah, QtCreator now requires Qt5, IIRC starting from version 3.3 (or 3.4?).

**Comment by briansprojects** [comment]
Ok. My target distro was openSUSE Tumbleweed so I used whatever was in their repositories.

**Comment by briansprojects** [comment]
I am still running into the same issue as before. I noticed that my QtCreator is installed at 

    /usr/lib/x86_64-linux-gnu/qtcreator 

and the script throws the following warning:

    Cannot access directory '/usr/lib/qtcreator/plugins/QtProject'

**Comment by hugopl** [comment]
If it throws this at the end, this is expected, see the README.

This is because QtCreator default setup is to move the compiled plugin library to the install destination, but if you are compiling the plugin against the system QtCreator this is not possible.

The fix? Just copy the .so file yourself to the requested location, or run make as root.
