### ISSUE TITLE
Sorry, can not find the QtCreator version.

### ISSUE THREAD

**Issue by seyedmmousavi** [hugopl/RubyCreator#64]
I have already a Qt from official site (installed using official installer).
In the Terminal when I run `./configure` it fails with `Sorry, can not find the QtCreator version.` message.
What is the problem?

**Comment by hugopl** [comment]
You probably do not have QtCreator installed on your system, RubyCreator is just a plugin to QtCreator, so you need to have QtCreator installed.

Pay attention to the version you are going to install too.

**Comment by seyedmmousavi** [comment]
But I installed QtCreator 4.1 using official installer.
Must I set some environment variables?

**Comment by hugopl** [comment]
It must be in the system path, take a look at the configure script.

**Comment by seyedmmousavi** [comment]
thank's a lot!
I created a bash script in `/usr/local/bin/qtcreator` with this content:
```
#!/usr/bin/env bash
~/Qt5.5.1/Qt\ Creator.app/Contents/MacOS/Qt\ Creator "$@"

```
then I make it executable using `chmod +x /usr/local/bin/qtcreator`.
now `./configure.rb` works correctly.
Thank you @hugopl 
(Note: My platform is Mac OS)

**Comment by seyedmmousavi** [comment]
another problem!
`cd build && make` returns with this error:
`make: *** No targets specified and no makefile found.  Stop.`
it seems to be bad configured.

**Comment by hugopl** [comment]
You have QtCreator 4.1 installed, so you need a RubyCreator version compatible with QtC4.1, try to compile the branch named `v4.1.0`.

Did you ran the `make` command inside the build directory?

 I never tried to compile it on a Mac (since I don't have one), only on Linux and Windows, so you will be the first one, hehe.

**Comment by hugopl** [comment]
Oops, just notice you did it.

**Comment by seyedmmousavi** [comment]
OK. I added Qt directory in the PATH environmental variable and then I re-ran `./configure`.
this time it gets me this warning: 
```
WARNING: DESTDIR: Cannot access directory '/usr/bin/Qt Creator.app/Contents/PlugIns'
Project configured under build directory, go there and call make.
```
I ignored it and `make` returned error: 
```
../editor/RubyQuickFixes.cpp:34:12: error: invalid operands to binary expression
      ('TextEditor::QuickFixOperations' and 'Ruby::SwitchStringQuotesOp *')
    result << operation;
    ~~~~~~ ^  ~~~~~~~~~
```

**Comment by hugopl** [comment]
Nice!

Qt4.2 changed the API, this error is because you are comping the master branch (which is compatible with QtC 4.2) against QtC 4.1, you can just use the v4.1.0 branch of RubyCreator or revert this patch https://github.com/hugopl/RubyCreator/commit/229ab05913e39d3b3d680d1f09609c002a6a3802 and try to compile again.

i.e. this line should be `result.append(operation)` on QtC 4.1.

**Comment by hugopl** [comment]
After the compilation finishes, you will need to manually copy the plugin file to '/usr/bin/Qt Creator.app/Contents/PlugIns', this was the reason of the warning in the beginning.

**Comment by seyedmmousavi** [comment]
thank you I will try it.

**Comment by seyedmmousavi** [comment]
the `/usr/bin/Qt Creator.app/Contents/PlugIns` path is not right. Because my Qt Creator is installed in `~/Qt5.5.1/` and also I placed my bash script in `/usrl/local/bin/qtcreator`.
So I manipulated `Makefile` in the `build` folder and I replaced any `/usr/bin/Qt Creator.app/` into `/Users/<my user name>/Qt5.5.1/Qt\ Creator.app/`. After that, `make` command works as expected.
Now Ruby plugin is available and active in the QtCreator.
I can see just a new option into `File > New File or Project... > Import Project ` named `Import Existing Ruby Project` is it all thing that I must see?
I tried to open an ruby file using QtCreator and it raised an error:
````
Rubocop not installed or not found, if you use rvm, check if rubocop is installed on your system ruby.
````
What is the problem?

**Comment by hugopl** [comment]
The plugin uses Rubocop to highlight syntax errors and other things detected by rubocop, however, if rubocop isn't found in the system path the plugin will work normally, just this feature will be disabled.

But I think I can close the issue, since you was able to compile and use the plugin. :-)

Thanks.

**Comment by seyedmmousavi** [comment]
Thank you.
You right.
